// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xalzyyjaosfrlyhvagxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbHp5eWphb3Nmcmx5aHZhZ3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTQ1NjEsImV4cCI6MjA3MjAzMDU2MX0.C2sc-8aCgj_X-fRTvGoHKPPaKFjOe-HjuKscX_QvcFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});